addons:
  apt:
    packages:
    - libgmp-dev
language: c
sudo: false
cache:
  directories:
  - $HOME/.local/bin
  - $HOME/.stack
os:
- linux
- osx
before_install:
- sh travis/install-stack.sh
- sh travis/install-ghr.sh
script:
- stack setup
- stack build
- stack test
after_success:
- sh travis/attach-binary.sh