name:                hascard
version:             0.3.0.1
github:              "Yvee1/hascard"
license:             BSD3
author:              "Steven van den Broek"
maintainer:          "stevenvdb@live.nl"
copyright:           "2020 Steven van den Broek"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            A TUI for reviewing notes using 'flashcards' written with markdown-like syntax.
category:            Application

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Hascard is a text-based user interface for reviewing notes using flashcards. Cards are written in markdown-like syntax. Please see the README file on GitHub at <https://github.com/Yvee1/hascard#readme> for more information.

dependencies:
- base >= 4.7 && < 5
- brick >= 0.52.1 && < 0.56
- containers > 0.6.0 && < 0.7
- directory >= 1.3.3 && < 1.4
- filepath >= 1.4.2 && < 1.5
- microlens >= 0.4.11 && < 0.5
- microlens-platform >= 0.4.1 && < 0.5
- mwc-random >= 0.14 && < 0.15
- optparse-applicative >= 0.15.1 && < 0.16
- ordered-containers >= 0.2.2 && < 0.3
- megaparsec >= 8.0.0 && < 8.1
- process >= 1.6.5 && < 1.7
- random-fu >= 0.2.7 && < 0.3
- strict >= 0.3.2 && < 0.4
- text >= 1.2.3 && < 1.3
- vector >= 0.12.0 && < 0.13
- vty >= 5.28.2 && < 5.31
- word-wrap >= 0.4.1 && < 0.5

library:
  source-dirs: src

executables:
  hascard:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hascard

tests:
  hascard-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hascard
